# Custom Language File for Launcher Customizer

[ejs.app]
title = "Metropolis Launcher"

[ejs.landing]
mediaGitHubURL = "https://desert-brush-1cd.notion.site/25cb91cfa38880898316e76b5dafe09d?v=25cb91cfa38881caab98000c184eacc1&source=copy_link"
mediaXURL = "https://desert-brush-1cd.notion.site/25cb91cfa38880898316e76b5dafe09d?v=25cb91cfa38881caab98000c184eacc1&source=copy_link"
mediaInstagramURL = "https://desert-brush-1cd.notion.site/25cb91cfa38880898316e76b5dafe09d?v=25cb91cfa38881caab98000c184eacc1&source=copy_link"
mediaYouTubeURL = "https://desert-brush-1cd.notion.site/25cb91cfa38880898316e76b5dafe09d?v=25cb91cfa38881caab98000c184eacc1&source=copy_link"
mediaDiscordURL = "https://discord.gg/7HjBtuEb2X"

[ejs.settings]
sourceGithubLink = "https://desert-brush-1cd.notion.site/25cb91cfa38880898316e76b5dafe09d?v=25cb91cfa38881caab98000c184eacc1&source=copy_link"
supportLink = "https://desert-brush-1cd.notion.site/25cb91cfa38880898316e76b5dafe09d?v=25cb91cfa38881caab98000c184eacc1&source=copy_link"

[ejs.welcome]
welcomeHeader = "메트로폴리스 서버"
welcomeDescription = "Metropolis는 현실 경제를 기반으로 한 Minecraft 서버입니다. 다양한 경제 시스템과 직업, 그리고 여러 가지 치장 아이템과 퀄리티 높은 커스텀 요소들을 통해 현실 속 도시 생활을 경험하실 수 있습니다. 단순한 생존을 넘어, 플레이어 간의 거래와 협력이 중심이 되는 새로운 세계가 여러분을 기다리고 있습니다."
welcomeDescCTA = "힐링하는 메트로폴리스 서버에서 즐거운 시간 보내시길 바랍니다."